//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaveTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRoles
    {
        public int UserRolesID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleNameID { get; set; }
    
        public virtual tblRoleNames tblRoleNames { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
